name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Build project
        run: mvn clean install -q

      - name: Run SpotBugs
        run: |
          mvn com.github.spotbugs:spotbugs-maven-plugin:spotbugs \
            -Dspotbugs.xmlOutput=true \
            -Dspotbugs.htmlOutput=true 

      - name: Upload SpotBugs reports
        uses: actions/upload-artifact@v4
        with:
          name: spotbugs-reports
          path: target/spotbugs-reports/

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Run Snyk Test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          snyk test --all-projects | tee target/snyk-report.txt
          snyk test --all-projects --json > target/snyk-report.json
          snyk-to-html -i snyk-report.json -o snyk-report.html

      - name: Upload Snyk reports
        uses: actions/upload-artifact@v4
        with:
          name: snyk-reports
          path: |
            target/snyk-report.html
            target/snyk-report.json
