name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build
        working-directory: ./
        run: mvn clean install -q

      - name: SpotBugs
        working-directory: ./
        run: |
          mvn com.github.spotbugs:spotbugs-maven-plugin:spotbugs \
            -Dspotbugs.xmlOutput=true \
            -Dspotbugs.htmlOutput=true \
            -Dspotbugs.outputDirectory=target/spotbugs-reports

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Test Snyk
        working-directory: ./
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          snyk test --all-projects --json > target/snyk-report.json

      - name: Upload Reports
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: |
            target/spotbugs-reports/
            target/snyk-report.json
